---
title: Tom Healy
timezone: America/New_York
collections:
  books:
    title: Books
    output: false
  essays:
    title: Essays
    output: true
  events:
    title: Events
    output: true
  poetry:
    title: Poetry
    output: true
  posts:
    title: Posts
    output: true
  prose:
    title: Prose
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    parent: "/events/"
    layout: event
- scope:
    path: ''
    type: essays
  values:
    parent: "/essays/"
    layout: page
- scope:
    path: ''
    type: reports
  values:
    parent: "/reports/"
url: http://tomhealy.siteleaf.net
permalink: pretty
taxonomies:
- Who
- What
- Where
- Why
