---
title: Tom Healy
url: http://tomhealy.siteleaf.net
timezone: Eastern Time (US & Canada)
permalink: pretty
taxonomies: [Who, What, Where, Why]
emptyArray: []
collections:
  uploads:
    title: Uploads
    output: true
  essays:
    output: true
  videos:
    output: true
  poetry:
    output: true
  events:
    output: true
  interviews-and-reviews:
    output: true
    permalink: "/interviews-and-reviews/:path"
  what-the-right-hand-knows:
    output: true
    permalink: "/poetry/what-the-right-hand-knows/:path"
  animal-spirits:
    output: true
    permalink: "/poetry/animal-spirits/:path"
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    parent: "/events/"
    layout: event
- scope:
    path: ''
    type: essays
  values:
    parent: "/essays/"
    layout: page
- scope:
    path: ''
    type: reports
  values:
    parent: "/reports/"
imgix: http://aplusa.imgix.net
permalink: pretty
